version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================
  # 🚀 FIRST-TIME SETUP
  # ============================================================

  bootstrap:
    desc: "🎯 Complete first-time setup: dependencies + services + automation"
    cmds:
      - echo "📦 Installing dependencies..."
      - uv sync
      - echo ""
      - echo "🔧 Starting background services..."
      - nohup bash scripts/start_aim.sh >/dev/null 2>&1 &
      - nohup bash scripts/voicevox_manager.sh start >/dev/null 2>&1 &
      - nohup uv run python scripts/discord_news_bot.py >/dev/null 2>&1 &
      - sleep 3
      - echo ""
      - echo "⚙️  Configuring automation..."
      - python scripts/automation.py --skip-cron
      - python scripts/automation.py --install-cron
      - echo ""
      - echo "✅ Bootstrap complete! Services running, cron installed."
      - echo ""
      - task services-status

  setup:
    desc: Install dependencies only
    cmds:
      - uv sync

  # ============================================================
  # 🎬 WORKFLOW & EXECUTION
  # ============================================================

  run:
    desc: Run main workflow (use -- to pass args)
    cmds:
      - uv run python -m src.main {{.CLI_ARGS}}

  youtube:run:
    desc: Run YouTube video generation workflow
    cmds:
      - uv run python -m apps.youtube.cli run

  youtube:dev:
    desc: Run YouTube workflow with debug logging
    cmds:
      - uv run python -m apps.youtube.cli run --log-level DEBUG

  thumbnail-test:
    desc: Test AI thumbnail generation with existing run ID
    cmds:
      - |
        RUN_ID={{.CLI_ARGS}}
        if [ -z "$RUN_ID" ]; then
          echo "Usage: task thumbnail-test -- <run_id>"
          echo "Example: task thumbnail-test -- 20251122_184042"
          exit 1
        fi
        source ~/.bashrc
        uv run python -c "
        from pathlib import Path
        from src.steps.thumbnail_ai import AIThumbnailGenerator
        run_id = '$RUN_ID'
        run_dir = Path('runs')
        if not (run_dir / run_id).exists():
            print(f'❌ Run directory not found: {run_dir / run_id}')
            exit(1)
        config = {'enabled': True, 'width': 1920, 'height': 1080, 'num_steps': 6}
        gen = AIThumbnailGenerator(run_id, run_dir, config)
        inputs = {'generate_script': str(run_dir / run_id / 'script.json'), 'analyze_metadata': str(run_dir / run_id / 'metadata.json')}
        output = gen.execute(inputs)
        print(f'✅ Generated: {output}')
        "

  # ============================================================
  # 🤖 AUTOMATION & SERVICES
  # ============================================================

  services:start:
    desc: Start all background services (Aim, Voicevox, Discord)
    cmds:
      - nohup bash scripts/start_aim.sh >/dev/null 2>&1 &
      - nohup bash scripts/voicevox_manager.sh start >/dev/null 2>&1 &
      - nohup uv run python scripts/discord_news_bot.py >/dev/null 2>&1 &
      - sleep 2
      - echo "✅ Services started in background"

  services:status:
    desc: Check status of all automation services
    cmds:
      - echo "=== 🔄 Running Processes ==="
      - ps aux | grep -E "(aim|voicevox|discord_news_bot)" | grep -v grep || echo "No services running"
      - echo ""
      - echo "=== 🐳 Docker Containers ==="
      - docker ps | grep voicevox || echo "Voicevox container not running"
      - echo ""
      - echo "=== ⏰ Cron Jobs ==="
      - crontab -l || echo "No cron jobs installed"

  automation:setup:
    desc: Setup automation with git pull, services, and cron installation
    cmds:
      - echo "📥 Pulling latest changes..."
      - git pull --no-rebase || echo "⚠️  Manual merge may be required"
      - echo ""
      - echo "🔧 Starting services..."
      - nohup bash scripts/start_aim.sh >/dev/null 2>&1 &
      - nohup bash scripts/voicevox_manager.sh start >/dev/null 2>&1 &
      - nohup uv run python scripts/discord_news_bot.py >/dev/null 2>&1 &
      - sleep 3
      - echo ""
      - echo "⚙️  Configuring automation..."
      - python scripts/automation.py --skip-cron
      - python scripts/automation.py --install-cron
      - echo ""
      - echo "✅ Automation setup complete!"
      - crontab -l

  automation:init:
    desc: Initialize automation services (without cron)
    cmds:
      - python scripts/automation.py --skip-cron

  automation:cron:
    desc: Install cron schedule for automated workflows
    cmds:
      - python scripts/automation.py --install-cron
      - echo "✅ Cron installed. Schedule:"
      - crontab -l

  discord:start:
    desc: Start Discord news bot
    cmds:
      - nohup uv run python scripts/discord_news_bot.py >/dev/null 2>&1 &
      - echo "✅ Discord bot started"

  voicevox:start:
    desc: Start Voicevox TTS engine
    cmds:
      - bash scripts/voicevox_manager.sh start

  voicevox:stop:
    desc: Stop Voicevox TTS engine
    cmds:
      - bash scripts/voicevox_manager.sh stop

  voicevox:status:
    desc: Check Voicevox status
    cmds:
      - bash scripts/voicevox_manager.sh status

  aim:import:
    desc: Import run data to Aim tracking
    cmds:
      - uv run python scripts/import_to_aim.py

  aim:dashboard:
    desc: Start Aim dashboard UI (blocking)
    cmds:
      - aim up --host 0.0.0.0 --port 43800

  # ============================================================
  # ✅ CODE QUALITY
  # ============================================================

  lint:
    desc: Run linting checks
    cmds:
      - uv run ruff check src tests apps

  lint:fix:
    desc: Auto-fix linting issues and format code
    cmds:
      - uv run ruff check --fix src tests apps
      - uv run ruff format src tests apps

  format:
    desc: Format code with ruff
    cmds:
      - uv run ruff format src tests apps

  # ============================================================
  # 🧪 TESTING
  # ============================================================

  test:
    desc: "Alias for test:fast"
    cmds:
      - task: test:fast

  test:fast:
    desc: "Run fast tests (skips FFmpeg/video rendering)"
    cmds:
      - uv run pytest tests -v -m "fast or not slow" --tb=short

  test:all:
    desc: "Run ALL tests (includes slow FFmpeg rendering)"
    cmds:
      - uv run pytest tests -v --tb=short

  # ============================================================
  # 📝 GIT WORKFLOWS
  # ============================================================

  git:status:
    desc: Show git status
    cmds:
      - git status

  git:add:
    desc: Stage all changes
    cmds:
      - git add .

  git:commit:
    desc: Commit with message (use -- "message")
    cmds:
      - git commit -m "{{.CLI_ARGS | default "Update"}}"

  git:push:
    desc: Push to remote
    cmds:
      - git push

  git:sync:
    desc: Add, commit, and push in one command
    cmds:
      - git add .
      - git commit -m "{{.CLI_ARGS | default "Update"}}"
      - git push

  # ============================================================
  # 🧹 MAINTENANCE
  # ============================================================

  clean:
    desc: Clean temporary files and caches
    cmds:
      - find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name .pytest_cache -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete
      - echo "✅ Cleaned cache files"

